// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW19H_benibJBDzktofIx0B1TRu34JyF4',
    appId: '1:1044808981300:web:87e77ffbd739161bf66361',
    messagingSenderId: '1044808981300',
    projectId: 'thws-announcements',
    authDomain: 'thws-announcements.firebaseapp.com',
    storageBucket: 'thws-announcements.appspot.com',
    measurementId: 'G-7VYPY3Y0XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlt2tTgikO-HpK2MQ7QmiO-7kf-7gbivI',
    appId: '1:1044808981300:android:d108d74b9d27872bf66361',
    messagingSenderId: '1044808981300',
    projectId: 'thws-announcements',
    storageBucket: 'thws-announcements.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAswXecw-cPGhUxf1w2cGoXahqnesTH0w8',
    appId: '1:1044808981300:ios:0c2e2a9049eed450f66361',
    messagingSenderId: '1044808981300',
    projectId: 'thws-announcements',
    storageBucket: 'thws-announcements.appspot.com',
    iosClientId: '1044808981300-r2k9dj4f8ge1kd2rd4uc7mt75tekinol.apps.googleusercontent.com',
    iosBundleId: 'com.example.twhsAnnouncements',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAswXecw-cPGhUxf1w2cGoXahqnesTH0w8',
    appId: '1:1044808981300:ios:0c2e2a9049eed450f66361',
    messagingSenderId: '1044808981300',
    projectId: 'thws-announcements',
    storageBucket: 'thws-announcements.appspot.com',
    iosClientId: '1044808981300-r2k9dj4f8ge1kd2rd4uc7mt75tekinol.apps.googleusercontent.com',
    iosBundleId: 'com.example.twhsAnnouncements',
  );
}
